import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Providers } from "@/providers";

const leagueSpartan = League_Spartan({
	variable: "--font-league-spartan",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${leagueSpartan.variable} h-full antialiased`}
			suppressHydrationWarning>
			<body className="min-h-full flex md:flex-row flex-col">
				<Providers>
					<Navbar />
					{children}
				</Providers>
			</body>
		</html>
	);
}
